# Generated by Django 4.2 on 2023-04-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_staffuser_staffs_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='staffs',
            name='staff_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='staffs.staffuser'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
