# Generated by Django 4.2 on 2023-04-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_remove_staffs_is_admin_alter_staffs_staff_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='staff_user',
        ),
    ]
