# Generated by Django 4.2 on 2023-04-30 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_staff_id'),
        ('staffs', '0004_remove_staffs_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, related_name='instructors', to='courses.courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffs.staffuser')),
            ],
        ),
    ]
