# Generated by Django 4.2 on 2023-04-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentuser_student_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.studentuser'),
        ),
    ]
